// File generated by FlutterFire CLI.
// This file is used to configure Firebase for the application.
// You will need to replace these values with your own Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu0YgNB3AcMfFh77Q6dyAUxvUgEu8kfmk',
    appId: '1:417689612674:web:644e7aaac2bc5f00a8df9b',
    messagingSenderId: '417689612674',
    projectId: 'authflow-aaa3c',
    authDomain: 'authflow-aaa3c.firebaseapp.com',
    storageBucket: 'authflow-aaa3c.firebasestorage.app',
    measurementId: 'G-69ZZN5S0G4',
  );

  // Replace these placeholder values with your actual Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMMztEiSXWDvhW_LD3prQaSSw3cijJ1c',
    appId: '1:417689612674:android:84930d9aa4d2c7dca8df9b',
    messagingSenderId: '417689612674',
    projectId: 'authflow-aaa3c',
    storageBucket: 'authflow-aaa3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIYfyzJJeVz9lUqAq6uXfuLaPRbFOtpko',
    appId: '1:417689612674:ios:c584fae2f381758ea8df9b',
    messagingSenderId: '417689612674',
    projectId: 'authflow-aaa3c',
    storageBucket: 'authflow-aaa3c.firebasestorage.app',
    iosBundleId: 'com.example.authflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIYfyzJJeVz9lUqAq6uXfuLaPRbFOtpko',
    appId: '1:417689612674:ios:c584fae2f381758ea8df9b',
    messagingSenderId: '417689612674',
    projectId: 'authflow-aaa3c',
    storageBucket: 'authflow-aaa3c.firebasestorage.app',
    iosBundleId: 'com.example.authflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu0YgNB3AcMfFh77Q6dyAUxvUgEu8kfmk',
    appId: '1:417689612674:web:4ff535f94aeda1e9a8df9b',
    messagingSenderId: '417689612674',
    projectId: 'authflow-aaa3c',
    authDomain: 'authflow-aaa3c.firebaseapp.com',
    storageBucket: 'authflow-aaa3c.firebasestorage.app',
    measurementId: 'G-R1VDZC75G7',
  );

}